name: Ejecutar scraper y guardar datos

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Diagnóstico - verificar archivos
        run: |
          echo "Directorio actual:"
          pwd
          echo "Contenido:"
          ls -la

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar scraper
        run: npm run scrape

      - name: Commit y push de data.json actualizado
  env:
    GH_TOKEN: ${{ secrets.GH_TOKEN }}
  run: |
    git config user.name 'github-actions'
    git config user.email 'github-actions@users.noreply.github.com'
    git add data.json
    git commit -m "Actualizar data.json automáticamente" || echo "Sin cambios"
    git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/${{ github.repository }}
    git push origin HEAD:main

