name: Ejecutar scraper y guardar datos

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Necesario para poder hacer push

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Diagnóstico - verificar archivos
        run: |
          echo "Directorio actual:"
          pwd
          echo "Contenido:"
          ls -la

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Instalar dependencias
        run: |
          npm install
          npm audit fix --force  # Opcional, si quieres resolver vulnerabilidades automáticamente

      - name: Ejecutar scraper principal (data.json)
        run: npm run scrape

      - name: Ejecutar publicaciones.js (publicaciones.json)
        run: node publicaciones.js

      - name: Commit y push de archivos actualizados
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add data.json publicaciones.json
          git diff --staged --quiet || git commit -m "Actualizar data.json y publicaciones.json automáticamente"
          git pull --rebase --autostash
          git push
