name: Ejecutar scraper y guardar datos

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Diagnóstico - verificar archivos
        run: |
          echo "Directorio actual:"
          pwd
          echo "Contenido:"
          ls -la

      - name: Instalar dependencias
        run: npm install
        working-directory: ${{ github.workspace }}

      - name: Ejecutar scraper
        run: npm run scrape
        working-directory: ${{ github.workspace }}

      - name: Commit y push de data.json actualizado
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@users.noreply.github.com'
          git add data.json
          git commit -m "Actualizar data.json automáticamente" || echo "Sin cambios"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

